# Generated by Django 5.0.4 on 2024-12-18 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0004_profile_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
