# Generated by Django 5.0.4 on 2024-12-15 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    # dependencies = [
    #     ('userManagement', '0009_alter_profile_user_delete_user'),
    # ]

    operations = [
        migrations.CreateModel(
            name='Tournement',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('won', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userManagement.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userManagement.profile')),
                ('tournement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameManagement.tournement')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_player_1', models.IntegerField(blank=True, null=True)),
                ('score_player_2', models.IntegerField(blank=True, null=True)),
                ('player_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matche_player_1', to='gameManagement.player')),
                ('player_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matche_player_2', to='gameManagement.player')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='gameManagement.player')),
                ('tournement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameManagement.tournement')),
            ],
        ),
    ]
