# Generated by Django 5.0.4 on 2024-12-16 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameManagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournement',
            old_name='won',
            new_name='won_id',
        ),
    ]
