# Generated by Django 5.0.4 on 2024-12-16 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameManagement', '0002_rename_won_tournement_won_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournement',
            old_name='won_id',
            new_name='won',
        ),
    ]
