# Generated by Django 5.0.4 on 2024-12-16 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameManagement', '0003_rename_won_id_tournement_won'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
