# Generated by Django 5.0.4 on 2024-12-17 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameManagement', '0004_alter_tournement_id'),
        # ('userManagement', '0009_alter_profile_user_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournement',
            name='won',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='won_tournament', to='userManagement.profile'),
        ),
    ]
