# Generated by Django 5.0.4 on 2024-12-17 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameManagement', '0005_alter_tournement_won'),
        # ('userManagement', '0009_rename_player_1_match_player1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournement',
            name='lose',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lose_tournament', to='userManagement.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournement',
            name='numberParticipants',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
