# Generated by Django 5.0.4 on 2024-12-17 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameManagement', '0006_tournement_lose_tournement_numberparticipants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='tournement',
        ),
    ]
