# Generated by Django 5.0.4 on 2024-12-17 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameManagement', '0007_remove_player_tournement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='tournement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gameManagement.tournement'),
        ),
    ]
