# Generated by Django 5.0.4 on 2024-12-17 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameManagement', '0008_alter_match_tournement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='player_1',
            new_name='player1',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='player_2',
            new_name='player2',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='score_player_1',
            new_name='score_player1',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='score_player_2',
            new_name='score_player2',
        ),
    ]
