# Generated by Django 5.0.4 on 2024-12-18 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameManagement', '0009_rename_player_1_match_player1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='loser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lose_matches', to='gameManagement.player'),
        ),
    ]
