# Generated by Django 5.0.4 on 2024-12-19 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameManagement', '0010_match_loser'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='end',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], default='inactive', max_length=10),
        ),
    ]
