# Generated by Django 5.0.4 on 2024-12-20 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameManagement', '0011_match_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='player1_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='player2_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
