# Generated by Django 5.0.4 on 2024-12-20 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameManagement', '0012_match_player1_name_match_player2_name'),
        # ('userManagement', '0009_alter_profile_user_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matche_player_2', to='userManagement.profile'),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='userManagement.profile'),
        ),
        migrations.AlterField(
            model_name='match',
            name='loser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lose_matches', to='userManagement.profile'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matche_player_1', to='userManagement.profile'),
        ),
        migrations.RemoveField(
            model_name='match',
            name='player1_name',
        ),
        migrations.RemoveField(
            model_name='match',
            name='player2_name',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
