# Generated by Django 5.0.4 on 2024-12-21 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameManagement', '0013_alter_match_player2_alter_match_winner_and_more'),
        ('userManagement', '0005_remove_profile_friends_delete_friendship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='tournement',
        ),
        migrations.AddField(
            model_name='tournement',
            name='end',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], default='false', max_length=10),
        ),
        migrations.AddField(
            model_name='tournement',
            name='match',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='match', to='gameManagement.match'),
        ),
        migrations.AlterField(
            model_name='match',
            name='end',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], default='false', max_length=10),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userManagement.profile')),
                ('tournement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameManagement.tournement')),
            ],
        ),
        migrations.AddField(
            model_name='tournement',
            name='player1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tournement_player_1', to='gameManagement.player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournement',
            name='player2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tournement_player_2', to='gameManagement.player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournement',
            name='player3',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tournement_player_3', to='gameManagement.player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournement',
            name='player4',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tournement_player_4', to='gameManagement.player'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tournement',
            name='lose',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lose_tournament', to='gameManagement.player'),
        ),
        migrations.AlterField(
            model_name='tournement',
            name='won',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='won_tournament', to='gameManagement.player'),
        ),
    ]
