# Generated by Django 5.0.4 on 2024-12-23 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameManagement', '0014_remove_match_tournement_tournement_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='player',
            name='tournement',
        ),
        migrations.RemoveField(
            model_name='tournement',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='tournement',
            name='lose',
        ),
        migrations.RemoveField(
            model_name='tournement',
            name='match',
        ),
        migrations.RemoveField(
            model_name='tournement',
            name='numberParticipants',
        ),
        migrations.RemoveField(
            model_name='tournement',
            name='start_date',
        ),
        migrations.AddField(
            model_name='match',
            name='tournement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gameManagement.tournement'),
        ),
        migrations.AlterField(
            model_name='tournement',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_1', to='gameManagement.player'),
        ),
        migrations.AlterField(
            model_name='tournement',
            name='player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_2', to='gameManagement.player'),
        ),
        migrations.AlterField(
            model_name='tournement',
            name='player3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_3', to='gameManagement.player'),
        ),
        migrations.AlterField(
            model_name='tournement',
            name='player4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_4', to='gameManagement.player'),
        ),
        migrations.AlterField(
            model_name='tournement',
            name='won',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameManagement.player'),
        ),
        migrations.CreateModel(
            name='T_match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_player1', models.IntegerField(blank=True, null=True)),
                ('score_player2', models.IntegerField(blank=True, null=True)),
                ('end', models.CharField(choices=[('true', 'True'), ('false', 'False')], default='false', max_length=10)),
                ('loser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loser', to='gameManagement.player')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='gameManagement.player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='gameManagement.player')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='gameManagement.player')),
            ],
        ),
        migrations.AddField(
            model_name='tournement',
            name='match1',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='match1', to='gameManagement.t_match'),
        ),
        migrations.AddField(
            model_name='tournement',
            name='match2',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='match2', to='gameManagement.t_match'),
        ),
        migrations.AddField(
            model_name='tournement',
            name='match3',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='match3', to='gameManagement.t_match'),
        ),
    ]
