# Generated by Django 5.0.4 on 2024-12-23 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameManagement', '0015_remove_player_profile_remove_player_tournement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_match',
            name='loser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loser', to='gameManagement.player'),
        ),
        migrations.AlterField(
            model_name='t_match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='gameManagement.player'),
        ),
    ]
