# Generated by Django 5.0.4 on 2024-12-23 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameManagement', '0016_alter_t_match_loser_alter_t_match_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournement',
            name='won',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gameManagement.player'),
        ),
    ]
