# Generated by Django 5.0.4 on 2024-12-23 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameManagement', '0018_alter_tournement_match3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='end',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], default='False', max_length=10),
        ),
        migrations.AlterField(
            model_name='t_match',
            name='end',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], default='False', max_length=10),
        ),
    ]
