# Generated by Django 5.0.4 on 2024-12-23 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameManagement', '0019_alter_match_end_alter_t_match_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournement',
            name='match3',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='match3', to='gameManagement.t_match'),
        ),
    ]
