# Generated by Django 5.0.4 on 2024-12-23 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameManagement', '0020_alter_tournement_match3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournement',
            name='match3',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match3', to='gameManagement.t_match'),
        ),
    ]
