# Generated by Django 5.0.4 on 2024-12-19 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friendsManagement', '0002_friendrequest_unique_friend_request_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='friendrequest',
            name='unique_friend_request',
        ),
        migrations.RemoveConstraint(
            model_name='friendrequest',
            name='unique_reverse_friend_request',
        ),
    ]
