services:
  
  db:
    init: true
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    env_file:
      - .env
    networks:
      - CP-network
    ports:
      - "5432:5432"
    restart: always

  web:    
    build:
      context: .
      dockerfile: server/CyberPong/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./server/CyberPong:/app/server/CyberPong
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - CP-network
    init: true
    restart: always

volumes:
  postgres_data:

networks:
  CP-network:
    name: CP-network
